Before building the image, you must set up your development environment with the necessary tools and system resources. 
This section outlines the required system specifications and installation steps for essential tools.

System Requirements
-------------------

To successfully build the image, ensure your system meets the following requirements:

- Minimum 200 GiB of free disk space
- At least 16 GiB of RAM
- Internet connection

Install the ``repo`` Tool
----------------------------

To install the ``repo`` tool, follow instructions from the `official Repo website <https://gerrit.googlesource.com/git-repo>`_.


Install the ``docker`` Tool
------------------------------

The installation process varies depending on your operating system. 
To install the ``docker`` tool, follow instructions from the `official Docker website <https://docs.docker.com/engine/install/>`_.
